#lab5 31st January 2025 by Arushi

#1 
data=read.csv("/home/ibab/Downloads/Heart.csv",header=TRUE)
print(data)

#2
# i)
print(dim(data))
# ii)
print(colnames(data))
# iii)
print(rownames(data))
# iv)
print(head(data,30))
# v)
lapply(data,table)
# vi)
data$ChestPain<- factor(data$ChestPain,levels=c("typical","asymptomatic","nonanginal"))
is.factor(data$ChestPain)
data$Thal<- factor(data$Thal,levels=c("reversable","fixed","normal"))
is.factor(data$Thal)
data$AHD<- factor(data$AHD,levels=c("Yes","No"))
is.factor(data$AHD)

# vii)
print(levels(data$ChestPain))
print(levels(data$Thal))
print(levels(data$AHD))

# viii)
print(nlevels(data$ChestPain))
print(nlevels(data$Thal))
print(nlevels(data$AHD))

#3
#i)
print(mean(data$Chol))
# ii)
print(mean(data$Chol))
# iii)
print(median(data$Chol))
# iv)
print(which.max(table(data$Chol)))
# v)
print(sd(data$Chol))
# vi)
print(summary(data$Chol))
# vii)
hist(data$Chol)
# viii)
library(moments)
print(skewness(data$Chol))
# ix)
print(kurtosis(data$Chol))
# x)
boxplot(data$Chol)
boxplot(data$Chol, range=0.1, horizontal=FALSE, border="purple", col= "pink")
boxplot(data$Chol, range=0.2, horizontal=FALSE, border="pink", col= "lavender")
boxplot(data$Chol, range=0.5, horizontal=FALSE, border="purple", col= "lavender")
# xi)
par(mfrow=c(1, 3))
boxplot(data$Chol)
boxplot(data$RestBP)
boxplot(data$RestECG)

#4
# i)
Chol_subset <- data[data$Chol > 20, ]
dim(Chol_subset)
print(Chol_subset)
# ii)
filter=data[c( 1,3,8,9,13,14,18,21),]
print(filter)
# iii)
female_indices <- which(data$Sex == "0")
print(female_indices)
female_subset <- subset(data, Sex == "0")
print(female_subset)
# iv)
new_column <- data$RestBP * data$RestECG / 234
new_dataframe <- data.frame(RestBP = data$RestBP, RestECG = data$RestECG, NewColumn = new_column)
print(new_dataframe)
# v)
female_subset <- subset(data, Sex == "0")
write.csv(female_subset, "/home/ibab/Downloads/lab4_female_Heart.csv", row.names = FALSE)
data_=read.csv("/home/ibab/Downloads/lab4_female_Heart.csv",header=TRUE)
print(data_)